print("Welcome to the tip Calculator!")
bill = float(input("What was the total bill? "))
tip = int(input("How much tip would you like to give? 10, 12, or 15 ? "))
split = int(input("How many peoples to split the bill? "))
pay_per_person = round((bill * (1 + tip/100))/split, 2)
print(f"Each person should pay {pay_per_person}")